return {
	{
		"stevearc/oil.nvim",
		opts = {},
		dependencies = { "nvim-tree/nvim-web-devicons" },
		config = function()
			require("plugins.config.oil")
			vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })

			vim.keymap.set("n", "<C-p>", function()
				require("oil").toggle_float()
			end, { noremap = true, silent = true })
		end,
	},

	"nvim-tree/nvim-web-devicons",
	-- {
	-- 	"tamago324/lir.nvim",
	-- 	config = function()
	-- 		require("plugins.config.lir")
	-- 	end,
	-- },
	-- "tamago324/lir-git-status.nvim",
	-- {
	-- 	"tamago324/lir-mmv.nvim",
	-- 	cond = function()
	-- 		return vim.fn.executable("mmv") == 1
	-- 	end,
	-- },
	-- {
	--   "nvim-neo-tree/neo-tree.nvim",
	--   dependencies = {
	--     "nvim-lua/plenary.nvim",
	--     "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
	--     "MunifTanjim/nui.nvim",
	--   },
	--   config = function()
	--     vim.fn.sign_define("DiagnosticSignError", { text = " ", texthl = "DiagnosticSignError" })
	--     vim.fn.sign_define("DiagnosticSignWarn", { text = " ", texthl = "DiagnosticSignWarn" })
	--     vim.fn.sign_define("DiagnosticSignInfo", { text = " ", texthl = "DiagnosticSignInfo" })
	--     vim.fn.sign_define("DiagnosticSignHint", { text = "󰌵", texthl = "DiagnosticSignHint" })
	--
	--     require("neo-tree").setup({
	--       default_component_configs = {
	--         indent = {
	--           indent_size = 2,
	--           padding = 1, -- extra padding on left hand side
	--           -- indent guides
	--           with_markers = true,
	--           indent_marker = "│",
	--           last_indent_marker = "└",
	--           highlight = "NeoTreeIndentMarker",
	--           -- expander config, needed for nesting files
	--           with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
	--           expander_collapsed = "",
	--           expander_expanded = "",
	--           expander_highlight = "NeoTreeExpander",
	--         },
	--         icon = {
	--           folder_closed = "",
	--           folder_open = "",
	--           folder_empty = "󰜌",
	--           default = "*",
	--           highlight = "NeoTreeFileIcon"
	--         },
	--         modified = {
	--           symbol = "[+]",
	--           highlight = "NeoTreeModified",
	--         },
	--         name = {
	--           trailing_slash = false,
	--           use_git_status_colors = true,
	--           highlight = "NeoTreeFileName",
	--         },
	--         git_status = {
	--           symbols = {
	--             added     = "[+]", -- or "✚", but this is redundant info if you use git_status_colors on the name
	--             modified  = "[]", -- or "", but this is redundant info if you use git_status_colors on the name
	--             deleted   = "[✖]", -- this can only be used in the git_status source
	--             renamed   = "[󰁕]", -- this can only be used in the git_status source
	--             -- Status type
	--             untracked = "[]",
	--             ignored   = "[]",
	--             unstaged  = "[󰄱]",
	--             staged    = "[]",
	--             conflict  = "[]",
	--           }
	--         },
	--         commands = {},
	--         window = {
	--           position = "left",
	--           width = 40,
	--           mapping_options = {
	--             noremap = true,
	--             nowait = true,
	--           },
	--           mappings = {
	--             ["<space>"] = {
	--               "toggle_node",
	--               nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
	--             },
	--             ["<2-LeftMouse>"] = "open",
	--             ["<cr>"] = "open",
	--             ["<esc>"] = "cancel", -- close preview or floating neo-tree window
	--             ["P"] = { "toggle_preview", config = { use_float = true } },
	--             ["l"] = "focus_preview",
	--             ["S"] = "open_split",
	--             ["s"] = "open_vsplit",
	--             ["t"] = "open_tabnew",
	--             ["w"] = "open_with_window_picker",
	--             ["C"] = "close_node",
	--             ["z"] = "close_all_nodes",
	--             ["a"] = {
	--               "add",
	--               config = { show_path = "none" }
	--             },
	--             ["A"] = "add_directory",
	--             ["d"] = "delete",
	--             ["r"] = "rename",
	--             ["y"] = "copy_to_clipboard",
	--             ["x"] = "cut_to_clipboard",
	--             ["p"] = "paste_from_clipboard",
	--             ["c"] = "copy", -- takes text input for destination, also accepts the optional config.show_path option like "add":
	--             ["m"] = "move", -- takes text input for destination, also accepts the optional config.show_path option like "add".
	--             ["q"] = "close_window",
	--             ["R"] = "refresh",
	--             ["?"] = "show_help",
	--             ["<"] = "prev_source",
	--             [">"] = "next_source",
	--             ["i"] = "show_file_details",
	--           }
	--         },
	--         filesystem = {
	--           filtered_items = {
	--             visible = true,
	--             hide_dotfiles = false,
	--             hide_gitignored = false,
	--           },
	--           follow_current_file = {
	--             enabled = true,
	--             leave_dirs_open = true,
	--           },
	--           group_empty_dirs = false,               -- when true, empty folders will be grouped together
	--           hijack_netrw_behavior = "open_default", -- netrw disabled, opening a directory opens neo-tree
	--           -- in whatever position is specified in window.position
	--           -- "open_current",  -- netrw disabled, opening a directory opens within the
	--           -- window like netrw would, regardless of window.position
	--           -- "disabled",    -- netrw left alone, neo-tree does not handle opening dirs
	--           use_libuv_file_watcher = false, -- This will use the OS level file watchers to detect changes
	--           -- instead of relying on nvim autocmd events.
	--           window = {
	--             mappings = {
	--               ["<bs>"] = "navigate_up",
	--               ["."] = "set_root",
	--               ["H"] = "toggle_hidden",
	--               ["/"] = "fuzzy_finder",
	--               ["D"] = "fuzzy_finder_directory",
	--               ["#"] = "fuzzy_sorter", -- fuzzy sorting using the fzy algorithm
	--               -- ["D"] = "fuzzy_sorter_directory",
	--               ["f"] = "filter_on_submit",
	--               ["<c-x>"] = "clear_filter",
	--               ["[g"] = "prev_git_modified",
	--               ["]g"] = "next_git_modified",
	--               ["o"] = { "show_help", nowait = false, config = { title = "Order by", prefix_key = "o" } },
	--               ["oc"] = { "order_by_created", nowait = false },
	--               ["od"] = { "order_by_diagnostics", nowait = false },
	--               ["og"] = { "order_by_git_status", nowait = false },
	--               ["om"] = { "order_by_modified", nowait = false },
	--               ["on"] = { "order_by_name", nowait = false },
	--               ["os"] = { "order_by_size", nowait = false },
	--               ["ot"] = { "order_by_type", nowait = false },
	--             },
	--             fuzzy_finder_mappings = { -- define keymaps for filter popup window in fuzzy_finder_mode
	--               ["<down>"] = "move_cursor_down",
	--               ["<C-n>"] = "move_cursor_down",
	--               ["<up>"] = "move_cursor_up",
	--               ["<C-p>"] = "move_cursor_up",
	--             },
	--           },
	--
	--           commands = {} -- Add a custom command or override a global one using the same function name
	--         },
	--         buffers = {
	--           follow_current_file = {
	--             enabled = true,
	--             leave_dirs_open = false,
	--           },
	--           group_empty_dirs = true, -- when true, empty folders will be grouped together
	--           show_unloaded = true,
	--           window = {
	--             mappings = {
	--               ["bd"] = "buffer_delete",
	--               ["<bs>"] = "navigate_up",
	--               ["."] = "set_root",
	--               ["o"] = { "show_help", nowait = false, config = { title = "Order by", prefix_key = "o" } },
	--               ["oc"] = { "order_by_created", nowait = false },
	--               ["od"] = { "order_by_diagnostics", nowait = false },
	--               ["om"] = { "order_by_modified", nowait = false },
	--               ["on"] = { "order_by_name", nowait = false },
	--               ["os"] = { "order_by_size", nowait = false },
	--               ["ot"] = { "order_by_type", nowait = false },
	--             }
	--           },
	--         },
	--       },
	--       git_status = {
	--
	--         window = {
	--           position = "float",
	--           mappings = {
	--             ["A"]  = "git_add_all",
	--             ["gu"] = "git_unstage_file",
	--             ["ga"] = "git_add_file",
	--             ["gr"] = "git_revert_file",
	--             ["gc"] = "git_commit",
	--             ["gp"] = "git_push",
	--             ["gg"] = "git_commit_and_push",
	--             ["o"]  = { "show_help", nowait = false, config = { title = "Order by", prefix_key = "o" } },
	--             ["oc"] = { "order_by_created", nowait = false },
	--             ["od"] = { "order_by_diagnostics", nowait = false },
	--             ["om"] = { "order_by_modified", nowait = false },
	--             ["on"] = { "order_by_name", nowait = false },
	--             ["os"] = { "order_by_size", nowait = false },
	--             ["ot"] = { "order_by_type", nowait = false },
	--           }
	--         }
	--       }
	--     })
	--   end
	-- }
}
